spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
  h2:
    console:
      enabled: false