spring:
  datasource:
    url: jdbc:mysql://${DM_CRM_SERVER:localhost}:${DM_CRM_PORT:3306}/${DM_CRM_DATABASE:customer_db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
  h2:
    console:
      enabled: false