spring:
  datasource:
    username: pNcPq11wWY
    password: XL6MaQl60X
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: mysql
server:
  port: 8090