spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/pNcPq11wWY
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
  h2:
    console:
      enabled: false