spring:
  datasource:
    username: ${DM_CRM_USERNAME:root}
    password: ${DM_CRM_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: ${DM_CRM_ACTIVE_PROFILE:h2}
server:
  port: 8090