spring:
  datasource:
    username: ${USER:root}
    password: ${PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: ${ACTIVE_PROFILE:mysql}
server:
  port: 8090