spring:
  datasource:
    url: jdbc:mysql://${SERVER:localhost}:${PORT:3306}/${DATABASE:customer_db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
  h2:
    console:
      enabled: false